### ISSUE TITLE
registerlm: date

### ISSUE THREAD

**Issue by Vectorist** [rogeruiz/budget#1]
I get the following error when I run ./registerlm checking:
date: invalid option -- 'v'
Try 'date --help' for more information.

I run Ubuntu 16 LTS.  I fixed it on my build, but I do not know if this would break the script on different builds.  The diff output follows:

--- a/scripts/registerlm
+++ b/scripts/registerlm
@@ -9,6 +9,6 @@ if [ -z $BUDGET_FILE ]; then
   exit 99
 fi
 
-THIRTY_DAYS_AGO=$( date -v -30d "+%Y/%m/%d" )
+THIRTY_DAYS_AGO=$( date --date='30 days ago' "+%Y/%m/%d" )
 
 $REGISTER_PATH --begin "$THIRTY_DAYS_AGO" "$@"

**Comment by rogeruiz** [comment]
oh this is a good catch. I run macOS, so this would most likely break my build. Running your new `date` command gives me the following errors.

```sh
$ date --date='30 days ago' "+%Y/%m/%d"
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

```

I can take a look into perhaps having a different `date` command that's more portable. But it may also just be better to perhaps leverage a base Docker image for all these scripts that way I don't need to worry about compatibility across different distributions. Thanks for reporting this. I'll leave it open @Vectorist but feel free to either close it or submit a PR with a check for whether the command was successful or not. I wouldn't want this to break on my machine 😉

**Comment by rogeruiz** [comment]
@Vectorist a possible way to deal with this is to update the Readme, and the scripts to run within this, to include how to leverage this Docker image: https://github.com/noazark/docker-ledger.

**Comment by rogeruiz** [comment]
Hey, @Vectorist I have a [work-in-progress PR](#2) with an Ubuntu image. Could you give that branch a try with your updated script and let me know if it still works?

**Comment by rogeruiz** [comment]
Closing this cause we now have :whale: Docker support. thanks @Vectorist
